### PR TITLE
Rewrite client to support high volume of topics

### PR DESCRIPTION
**Pull request by mnorkin**
Implement high performant metadata read from kafka cluster.

Previous implementation looped over all the topics, which it received from kafka cluster. Current implementation fetches only metadata by topic, so no loop over all topics is required.

* Rewrote couple of tests to reduce dependencies between tests
* Added more test to prove single instance multi topic publish/ consume/ group consume
* Wrote a kafka testkit to dynamically create topics. Now there is no need to download, run kafka and create topics for tests to work - just `npm run test`
* No API changes to the client

### CODE REVIEW

**Comment by mnorkin** [comment]
New PR, because old one was merged by mistake https://github.com/oleksiyk/kafka/pull/234

**Comment by mnorkin** [comment]
https://github.com/oleksiyk/kafka/pull/234#issuecomment-441986061

> And can you please revert the ability to run tests locally, without Doker.

@oleksiyk this means what tests will be not isolated from each other and for failed tests will have influence for not failing tests.

**Comment by oleksiyk** [comment]
> and for failed tests will have influence for not failing tests.

Sorry, I'm not sure I understand, what do you mean?

**Comment by mnorkin** [comment]
> Sorry, I'm not sure I understand, what do you mean?

I can give you an example. Please correct me if I'm wrong.

Test `A` and `B` is in the same group. Both of each publishes one message.

Test run 1:
Test `A` publishes one message to consumer and asserts that consumer handler was called only once. Test passed.
Test `B` publishes one message to the consumer and fails.

Test run 2:
Test `A` publishes one message to consumer and asserts that  consumer handler was called only once. Test failed, because consumer in test `A` also received a message from failed test `B`.

In dockerized kafka testkit, testkit spins a new instance of kafka every time, so every test run starts from clean offset. Also, docker gives you nice ability to dynamically create topics. Now, every test group creates the topics it needs. No need to create any topics by hand.

**Comment by oleksiyk** [comment]
> Test run 1:
Test A publishes one message to consumer and asserts that consumer handler was called only once. Test passed.
Test B publishes one message to the consumer and fails.
Test run 2:
Test A publishes one message to consumer and asserts that consumer handler was called only once. Test failed, because consumer in test A also received a message from failed test B.


Well I don't see any problem here. Consumers in all such tests are initialised to the end offset of the topic on each startup. 

> Can you please explain why you don't want dockerized kafka? Tests do run locally, on development machine.

Simple. I don't have enough power to spawn docker/kafka instances for each test. My mbp is already quite busy.

**Comment by mnorkin** [comment]
> Simple. I don't have enough power to spawn docker/kafka instances for each test. My mbp is already quite busy.

It's for every test run, not for every test.

**Comment by oleksiyk** [comment]
Anyway. Thats my average runtime with current project, docker doesn't fit here:
image

Also, this change is not within PR topic.

**Comment by mnorkin** [comment]
Ok, I'm closing this

**Pull request closed without merging**
