### PR TITLE
SSL Support

### PR DESCRIPTION
**Pull request by hunterloftis**
This PR adds SSL support and [documentation](https://github.com/hunterloftis/kafka/blob/master/README.md#ssl).

All current tests continue to pass in non-SSL environments (as you can see in Travis), and they now also pass over an SSL connection. If you'd like to chat about reproducing the SSL environment so you can test it yourself, please feel free to reach out to me at hunter@heroku.com and I'll help you get set up.

Also, how do you feel about eventually migrating tests to something like a Docker environment so we could run the whole suite over both an SSL-enabled and a non-SSL connection? I'd be happy to help with that if it's something you're interested in.

I made two changes for more portable testing:

1. I added `client.brokerList` as an intermediate property that's mapped in the Client constructor, before `init()` is called and transforms `brokerList` into an array of live Connections (`client.initialBrokers`). This is so we can write tests for parsing the broker list that don't have to make a networking attempt with the broker. With that change, the parsing happens independently of the connecting so we can run tests against non-localhost brokers (otherwise, running tests off localhost will fail, since `client.init()` will fail).

2. I hope you don't mind that I removed a time-based assert in the producer test. Checking for a time close to 500ms works fine when testing on localhost, but testing across a network introduces randomness that made the test unreliable.

### CODE REVIEW

**Comment by oleksiyk** [comment]
Well done! I'm going to review and try it in next couple of days. I was actually going to add SSL support for version 3.0 but its really great you already did it! 👍 

Regarding the time based test. Without that time based assert this test doesn't actually test the number of producer retries which was its primary task. Of course time based assertion did it indirectly and was very dependant on latency issues. This test must be changed to using spies. I can do that.

**Comment by oleksiyk** [comment]
Can you move (reopen) this PR to the 3.0 branch? If not, I can merge it manually myself, not a problem. I would like SSL to be part of 3.0.

**Comment by hunterloftis** [comment]
I can; currently there's a conflict with the 3.0 branch, so I'll need to sort that out first.

**Comment by hunterloftis** [comment]
@oleksiyk: https://blog.heroku.com/archives/2016/4/26/announcing-heroku-kafka-early-access

**Comment by oleksiyk** [comment]
I've added slightly different implementation of SSL support into 3.0 branch as well as Travis SSL/PLAINTEXT testing.

**Comment by hunterloftis** [comment]
Nice! I'll close this then and check that branch out.

**Comment by ccnixon** [comment]
Hi @oleksiyk - any timeline on when 3.0 will be released?

**Comment by oleksiyk** [comment]
@ccnixon I will get back to no-kafka in mid September.

**Pull request closed without merging**
