### PR TITLE
Add typings for typescript

### PR DESCRIPTION
**Pull request by jemmyw**

### CODE REVIEW

**Comment by oleksiyk** [comment]
Can you please provide some description for this? I have never used Typescript so have no idea what these changes do.

**Comment by jemmyw** [comment]
I'm withdrawing this as it's not quite up to scratch.

**Comment by sagax85** [comment]
that's a pity, would be awesome to get typings for this project!

**Comment by jemmyw** [comment]
@sagax85 my typings are here https://github.com/jemmyw/typed-no-kafka and you can install them with typings install --save github:jemmyw/typed-no-kafka#1effb1b

I will contribute them to the typings repo when they're in better shape.

**Pull request closed without merging**
